export const header = [
  {
    id: 0,
    title: 'LinkedIn',
    icon: '/assets/icons/linkedin.svg',
    link: 'https://www.linkedin.com/in/ginthozan-v/',
  },
  {
    id: 1,
    title: 'GitHub',
    icon: '/assets/icons/github.svg',
    link: 'https://github.com/ginthozan-v',
  },
  {
    id: 2,
    title: 'Whatsapp',
    icon: '/assets/icons/whatsapp.svg',
    link: 'https://wa.me/+940777453835',
  },
  {
    id: 3,
    title: 'Phone',
    icon: '/assets/icons/phone.png',
    link: 'tel:+310613364133',
  },
];

export const techStack = [
  {
    id: 0,
    title: 'react',
    icon: '/assets/icons/tech-stack/react-original.svg',
  },
  {
    id: 1,
    title: 'next-js',
    icon: '/assets/icons/tech-stack/nextjs-original-wordmark.svg',
  },
  {
    id: 2,
    title: 'javascript',
    icon: '/assets/icons/tech-stack/javascript-original.svg',
  },
  {
    id: 3,
    title: 'html5',
    icon: '/assets/icons/tech-stack/html5-original.svg',
  },
  {
    id: 4,
    title: 'css3',
    icon: '/assets/icons/tech-stack/css3-original.svg',
  },
  {
    id: 5,
    title: 'sass',
    icon: '/assets/icons/tech-stack/sass-original.svg',
  },
  {
    id: 6,
    title: 'tailwindcss',
    icon: '/assets/icons/tech-stack/tailwindcss-original.svg',
  },
  {
    id: 7,
    title: 'shopify',
    icon: '/assets/icons/tech-stack/shopify.svg',
  },
];

export const experience = [
  {
    id: 0,
    years: '2019 - 2020',
    company: 'Appz Makers',
    location: 'Colombo, Sri Lanka',
    role: 'Web Developer & Designer (Freelance)',
    techs: [
      'Laravel',
      'PHP',
      'HTML',
      'CSS',
      'Javascript',
      'MySQL',
      'Bootstrap',
      'Git',
    ],
    description:
      'Worked on multiple projects including Static Websites, Web applications and Graphic designing',
    responsibilities: [
      'Worked closely with the CEO and Stackeholders',
      'Invloded in requirement gathering, project planning and development',
      'Involved in deploying the application to a shared host.',
      'Involved in social media marketing.',
      'Designed art works, broachers, flyers for small business',
    ],
    projects: [],
  },
  {
    id: 1,
    years: '2020 Feb - 2021 Oct',
    company: 'Intersoft International Solutions',
    location: 'Jaffna, Sri Lanka',
    role: 'Fullstack Developer',
    techs: [
      'ASP .NET',
      'MVC',
      'C#',
      'Xamarin',
      'Javascript',
      'JQuery',
      'Ajax',
      'Bootstrap',
      'SQL Server',
      'TFS',
    ],
    description: 'Collaborated on Business Dispatch Logistics system software.',
    responsibilities: [
      'Maintaining the current logistic software',
      'Developed new features to the system for example inventory ordering when the stock quantity is low',
      'Involved in QA and bug fixes',
      'Helped improving their frontend user interface',
      'Developed a new web app with modern user interface to report generation and displaying statistics using Chart.js',
    ],
    projects: [],
  },
  {
    id: 2,
    years: '2022 Mar - 2023 Jul',
    company: 'Boolean labs',
    location: 'Colombo, Sri Lanka',
    role: 'Senior Frontend Developer (Remote)',
    techs: [
      'Next.js',
      'Typescript',
      'Tailwindcss',
      'Github',
      'Monorepo',
      'Agile',
    ],
    description:
      "MYT is a comprehensive portal for Mauritius Telecom's wide range of services, offering solutions for home, mobile, business, and financial needs",
    responsibilities: [
      'Led the development of significant portions of the CMS site and various components for the customer-facing site.',
      'Translated Figma designs into responsive React components.',
      'Developed and implemented features based on user stories from confluence.',
      'Created authentication routes.',
      'Designed and deployed a developer-friendly solution for dynamic form creation to accelerate development.',
      'Integrated REST APIs.',
      'Customized WSO2 Authentication UI to match the web portal theme.',
      'Adhered to agile practices and methodologies.',
      'Managed and tracked tasks using Jira, including handling tickets and maintaining documentation on Confluence.',
      'Mentored and guided junior developers.',
    ],
    projects: [],
  },
  {
    id: 3,
    years: '2021 Oct - 2023 Aug',
    company: 'Flatline Agency',
    location: 'Amsterdam, Netherlands',
    role: 'Frontend Developer (Remote)',
    techs: [
      'Next.js',
      'HTML',
      'CSS',
      'Tailwindcss',
      'Ionic',
      'Strapi',
      'Github',
    ],
    description:
      'Contributed to various projects.',
    responsibilities: [
      'Maintaining the current front-end of ongoing projects and developing new projects from scratch',
      'Translated wireframes into UI components',
      "REST API Integrations",
      'Collaborated with cross-functional teams',
      'Integrated APIs',
      'Following agile practices',
      'Mentored junior developers',
    ],
    projects: [
      {
        title: 'MISE',
        type: 'img',
        thumbnail: '/assets/projects/MISE.jpeg',
      },
      // {
      //   title: 'LAB 21',
      //   type: 'video',
      //   thumbnail: 'https://drive.google.com/file/d/1oK0qaltcAeWGDtU_k4IPDRPMKp49eljq/preview',
      // },
      // {
      //   title: 'YustInfra',
      //   type: 'video',
      //   thumbnail: '/assets/projects/yustinfra.mov',
      // },
    ],
  },
  {
    id: 4,
    years: '2023 Sep - Present',
    company: 'Flatline Agency',
    location: 'Amsterdam, Netherlands',
    role: 'Senior Frontend Developer',
    techs: [
      'Shopify',
      'Liquid',
      'HTML',
      'CSS',
      'JavaScript',
      'Storefront API',
      'REST API',
      'GraphQL',
      'Github',
    ],
    description:
      'Contributing to various Shopify eCommerce stores like Oger, Natural High & Noord Code.',
    responsibilities: [
      'Worked on leading brand stores in the Netherlands',
      'Maintaining the current front-end of clients stores',
      'Implementing new features',
      'Build a new front-end from start to end for new stores',
      'Translated wireframes into reusable UI components',
      'Collaborated with cross-functional teams',
      'Optimizing Shopify site performance and page load speed',
      'Integrated Shopify storefront APIs',
      'Following agile practices',
      'Mentored junior developers',
    ],
    projects: [
      {
        title: 'ESUALS',
        type: 'img',
        thumbnail: '/assets/projects/ESUALS.jpeg',
      },
      {
        title: 'SRFace',
        type: 'img',
        thumbnail: '/assets/projects/SRFACE.jpeg',
      },
      {
        title: 'Oger',
        type: 'img',
        thumbnail: '/assets/projects/OGER.jpeg',
      },
      {
        title: 'Balr',
        type: 'img',
        thumbnail: '/assets/projects/BALR.jpeg',
      },
    ],
  },
];
